2025-04-14 22:53:44,119 Worker rq:worker:eedbcc2e7a764615a1d75083c847b2bb: Redis connection timeout, quitting...
2025-04-14 23:00:06,078 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
2025-04-14 23:09:40,054 Worker rq:worker:6b29d3bccf7a4cc4ad085ea9c95e0c02: Redis connection timeout, quitting...
2025-04-14 23:13:13,438 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
2025-04-14 23:22:04,391 Worker rq:worker:7b2dabce272c4c24a80727742d0943a2: Redis connection timeout, quitting...
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/bin/python: Error while finding module specification for 'frappe.utils.bench_helper' (ModuleNotFoundError: No module named 'frappe')
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/utils.py:128: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.datetime.utcnow()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
        main()self.run()

  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1799, in run
    click.Group(commands=commands)(prog_name="bench")
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
        return self.main(*args, **kwargs)
           ^^^^^^^^^           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 1082, in main
^^^^^    rv = self.invoke(ctx)^
^         ^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
^^^^    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1542, in parse_response
^    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1518, in _execute
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                         return conn.retry.call_with_retry(
              ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/retry.py", line 49, in call_with_retry
^^^^^    fail(error)
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1520, in <lambda>
^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^    return ctx.invoke(self.callback, **ctx.params)^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
^^^^
    raise error
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^    return do()
           ^^^^^^^^
^^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
^^^^^^^^^^^^^            ^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/apps/frappe/frappe/commands/scheduler.py", line 205, in start_worker
^^^^^^    start_worker(^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/apps/frappe/frappe/utils/background_jobs.py", line 318, in start_worker
^^^    worker.work(
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/worker.py", line 456, in work
^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1536, in try_read
    self.teardown()
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/worker.py", line 1046, in teardown
    if not conn.can_read(timeout=timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 861, in can_read
    self.register_death()
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 2120, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/retry.py", line 49, in call_with_retry
        return self._parser.can_read(timeout)
           ^^^^^^^fail(error)
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 2122, in <lambda>
^^^^^^^^^^^^^^    ^lambda error: self._disconnect_raise_reset(conn, error),^
^ ^^ ^ ^ ^ ^ 
   File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 444, in can_read
        return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ^^^^^^^^^ ^  ^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^^^^^^^^^^^^^^^^^
^  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 455, in read_from_socket
^^^^    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
^^^^redis.exceptions.ConnectionError: Connection closed by server.
^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 2121, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1975, in _execute_transaction
    self.parse_response(connection, "_")
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 2060, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 874, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 493, in read_response
    self.read_from_socket()
  File "/home/thanhkhaii/frappe-nutrition/frappe-nutrition/env/lib/python3.12/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
